maxpool只有最大的地方有梯度，avgpool梯度均分

In [14]:
import torch
import torch.nn as nn

avgpool2d = nn.AvgPool2d(2, stride=2)
maxpool2d = nn.MaxPool2d(2, stride=2)
x = torch.rand(1, 3, 4, 4, requires_grad=True)
print(x)
y = maxpool2d(x)
print(y)
loss = (y**2).sum()
loss.backward()
print(x.grad)
x.grad.zero_()
y = avgpool2d(x)
loss = (y**2).sum()
loss.backward()
print(x.grad)

tensor([[[[0.2521, 0.5060, 0.8401, 0.1261],
          [0.8323, 0.5838, 0.2315, 0.4380],
          [0.3248, 0.2849, 0.5876, 0.8412],
          [0.2128, 0.5837, 0.9993, 0.4756]],

         [[0.4317, 0.5821, 0.6460, 0.4269],
          [0.6415, 0.1232, 0.8315, 0.9321],
          [0.9636, 0.6495, 0.9636, 0.1808],
          [0.8513, 0.9871, 0.3428, 0.5229]],

         [[0.2581, 0.6607, 0.8517, 0.0166],
          [0.0856, 0.6486, 0.2652, 0.7439],
          [0.1237, 0.0324, 0.3340, 0.0087],
          [0.1802, 0.5922, 0.3153, 0.1049]]]], requires_grad=True)
tensor([[[[0.8323, 0.8401],
          [0.5837, 0.9993]],

         [[0.6415, 0.9321],
          [0.9871, 0.9636]],

         [[0.6607, 0.8517],
          [0.5922, 0.3340]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)
tensor([[[[0.0000, 0.0000, 1.6802, 0.0000],
          [1.6646, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 1.1675, 1.9985, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000],
       