https://pytorch.org/docs/2.2/generated/torch.split.html#torch.split

In [1]:
import torch

a = torch.arange(24).reshape(2, 3, 4)

In [2]:
torch.split(a, 2, dim=0)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),)

In [3]:
torch.split(a, 2, dim=1)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19]]]),
 tensor([[[ 8,  9, 10, 11]],
 
         [[20, 21, 22, 23]]]))

In [4]:
torch.split(a, [1,3], dim=-1)

(tensor([[[ 0],
          [ 4],
          [ 8]],
 
         [[12],
          [16],
          [20]]]),
 tensor([[[ 1,  2,  3],
          [ 5,  6,  7],
          [ 9, 10, 11]],
 
         [[13, 14, 15],
          [17, 18, 19],
          [21, 22, 23]]]))